---
- name: Gather facts and configure SNMP
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Gather facts (IOS or NX-OS)
      ios_facts:
        gather_subset: all
      when: ansible_network_os == 'ios'

    - name: Gather facts for NX-OS
      nxos_facts:
        gather_subset:
          - default
      when: ansible_network_os == 'nxos'

    - name: Display the device hostname and software version
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"

    - name: Configure SNMP location on IOS
      ios_config:
        lines:
          - snmp-server location LAB-SAM
      when: ansible_network_os == 'ios'

    - name: Configure SNMP location on NX-OS
      nxos_config:
        lines:
          - snmp-server location LAB-SAM
      when: ansible_network_os == 'nxos'

    - name: Save running config to startup config (IOS only)
      ios_config:
        save_when: always
      when: ansible_network_os == 'ios'