---
all:
  hosts:
  children:
    routers:
      hosts:
        r1:
          ansible_host: 192.168.1.154
          ansible_network_os: ios
#        r2:
#          ansible_host: 192.168.7.161
#          ansible_network_os: ios
#        r3:
#          ansible_host: 192.168.7.162
#          ansible_network_os: ios
    switches:
      hosts:
        nx-sw1:
          ansible_host: 192.168.7.163
          ansible_network_os: nxos
        ios-sw1:
          ansible_host: 192.168.7.164
          ansible_network_os: ios
