---
- name: Gather network device information
  hosts: routers
  gather_facts: false
  connection: network_cli

  tasks:
  - name: View software version
    ios_command:
      commands: show version
    register: versions
    when: ansible_network_os == 'ios'
  
  - name: View configured syslog servers
    ios_command:
      commands: show run | i logging host
    register: syslogservers
    when: ansible_network_os == 'ios'

  - name: Printing out configured syslog hosts
    debug:
      var: syslogservers.stdout_lines
